// Icon components using lucide-react
import {
  Search,
  ScanBarcode,
  Heart,
  User,
  LogOut,
  Lock,
  Unlock,
  AlertCircle,
  CheckCircle,
  XCircle,
  Star,
  Share2,
  Menu,
  X,
  ChevronRight,
  Home,
  Package,
  ShoppingCart,
  Camera,
  TrendingUp,
  Award,
  Shield,
  Info,
  ExternalLink,
  Download,
  Bell,
  Settings,
  CreditCard,
  Filter,
  ArrowRight,
  Check,
  Loader2,
  Mail,
  Eye,
  EyeOff,
  Apple,
  Cookie,
  Milk,
  Coffee,
  Baby,
  Wheat,
  Newspaper,
  FileText,
  Calendar,
  Clock,
} from 'lucide-react';

export const Icons = {
  search: Search,
  scan: ScanBarcode,
  heart: Heart,
  user: User,
  logout: LogOut,
  lock: Lock,
  unlock: Unlock,
  alert: AlertCircle,
  check: CheckCircle,
  xCircle: XCircle,
  star: Star,
  share: Share2,
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  home: Home,
  package: Package,
  cart: ShoppingCart,
  camera: Camera,
  trending: TrendingUp,
  award: Award,
  shield: Shield,
  info: Info,
  external: ExternalLink,
  download: Download,
  bell: Bell,
  settings: Settings,
  card: CreditCard,
  filter: Filter,
  arrowRight: ArrowRight,
  checkmark: Check,
  spinner: Loader2,
  mail: Mail,
  eye: Eye,
  eyeOff: EyeOff,
  // Food categories
  apple: Apple,
  cookie: Cookie,
  milk: Milk,
  coffee: Coffee,
  baby: Baby,
  wheat: Wheat,
  // Blog icons
  newspaper: Newspaper,
  fileText: FileText,
  calendar: Calendar,
  clock: Clock,
};
