// Icon components using lucide-react
import {
  Search,
  ScanBarcode,
  Heart,
  User,
  LogOut,
  Lock,
  Unlock,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Star,
  Share2,
  Menu,
  X,
  ChevronRight,
  Home,
  Package,
  ShoppingCart,
  Camera,
  TrendingUp,
  TrendingDown,
  Award,
  Shield,
  ShieldCheck,
  Info,
  ExternalLink,
  Download,
  Bell,
  Settings,
  CreditCard,
  Filter,
  ArrowRight,
  Check,
  Loader2,
  Mail,
  Eye,
  EyeOff,
  Apple,
  Cookie,
  Milk,
  Coffee,
  Baby,
  Wheat,
  Newspaper,
  FileText,
  Calendar,
  Clock,
  Book,
  Brain,
  Leaf,
  Lightbulb,
  Smartphone,
  Send,
  Keyboard,
  Sprout,
  Factory,
  ThumbsUp,
  ThumbsDown,
  Droplet,
  Fish,
  RefreshCw,
  Barcode,
  Utensils,
  Beaker,
  ChefHat,
  Image,
} from 'lucide-react';

export const Icons = {
  search: Search,
  scan: ScanBarcode,
  barcode: ScanBarcode,
  heart: Heart,
  user: User,
  logout: LogOut,
  lock: Lock,
  unlock: Unlock,
  alert: AlertCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  check: CheckCircle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  star: Star,
  share: Share2,
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  home: Home,
  package: Package,
  cart: ShoppingCart,
  camera: Camera,
  trending: TrendingUp,
  trendingDown: TrendingDown,
  award: Award,
  shield: Shield,
  shieldCheck: ShieldCheck,
  info: Info,
  external: ExternalLink,
  download: Download,
  bell: Bell,
  settings: Settings,
  card: CreditCard,
  filter: Filter,
  arrowRight: ArrowRight,
  checkmark: Check,
  spinner: Loader2,
  loader: Loader2,
  mail: Mail,
  eye: Eye,
  eyeOff: EyeOff,
  keyboard: Keyboard,
  sprout: Sprout,
  factory: Factory,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  droplet: Droplet,
  fish: Fish,
  refreshCw: RefreshCw,
  utensils: Utensils,
  beaker: Beaker,
  flask: Beaker, // Using Beaker as Flask (Flask not available in lucide-react)
  chef: ChefHat,
  image: Image,
  // Food categories
  apple: Apple,
  cookie: Cookie,
  milk: Milk,
  coffee: Coffee,
  baby: Baby,
  wheat: Wheat,
  // Blog icons
  newspaper: Newspaper,
  fileText: FileText,
  calendar: Calendar,
  clock: Clock,
  book: Book,
  brain: Brain,
  leaf: Leaf,
  lightbulb: Lightbulb,
  smartphone: Smartphone,
  send: Send,
};

// Export all icons as named exports too
export {
  Search,
  ScanBarcode,
  ScanBarcode as Barcode,
  Heart,
  User,
  LogOut,
  Lock,
  Unlock,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Star,
  Share2,
  Menu,
  X,
  ChevronRight,
  Home,
  Package,
  ShoppingCart,
  Camera,
  TrendingUp,
  TrendingDown,
  Award,
  Shield,
  ShieldCheck,
  Info,
  ExternalLink,
  Download,
  Bell,
  Settings,
  CreditCard,
  Filter,
  ArrowRight,
  Check,
  Loader2,
  Mail,
  Eye,
  EyeOff,
  Apple,
  Cookie,
  Milk,
  Coffee,
  Baby,
  Wheat,
  Newspaper,
  FileText,
  Calendar,
  Clock,
  Book,
  Brain,
  Leaf,
  Lightbulb,
  Smartphone,
  Send,
  Keyboard,
  Sprout,
  Factory,
  ThumbsUp,
  ThumbsDown,
  Droplet,
  Fish,
  RefreshCw,
  Utensils,
  Beaker,
  ChefHat as Chef,
  Image,
};
